repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: detect-private-key
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      # Run the formatter and fix code styling
    - id: ruff-format

    # Run the linter and fix what is possible
    - id: ruff
      args: ['--fix']